services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: videos-a10a-app
    container_name: videos-a10a-app
    env_file:
      - .env
      - .env.local
    command: sleep infinity
    volumes:
      - ..:/workspace:cached
    ports:
      - 3000:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: mysql:8
    container_name: videos-a10a-app-db
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_TCP_PORT: 3306
      MYSQL_DATABASE: "videos_a10a_app"
    ports:
      - 3306:3306
volumes:
  dbdata:
