name: Update Er Diagram

on:
  push:
    branches:
      - main
    paths:
      - prisma/migrations/**
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  schema:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: schemaspy_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 2s
          --health-timeout 2s
          --health-retries 100

    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - uses: actions/checkout@v4

      - name: run migrate
        run: |
          go run -mod=mod ariga.io/atlas/cmd/atlas migrate apply \
            --dir file://${PWD}/ent/migrate/migrations \
            --url mysql://root@127.0.0.1:3306/genbago

      - name: run schemaspy
        run: |
          mkdir -p -m 777 ${PWD}/er
          docker run \
            --volume ${PWD}/er:/output \
            --net=${{ job.container.network }} \
            schemaspy/schemaspy:latest \
              -t mysql \
              -host db \
              -port 3306 \
              -u root \
              -db schemaspy_db \
              -s videos_a10a_app \
              -vizjs
          sudo chown -R runner:docker ${PWD}/er

      - uses: peter-evans/create-pull-request@v5
        with:
          add-paths: |
            er/**
          author: GitHub Action [bot] <noreply@github.com>
          committer: GitHub Action [bot] <noreply@github.com>
          branch: github-actions/update-er
          branch-suffix: short-commit-hash
          commit-message: auto generate er diagram
          title: auto generate er diagram
